(function(r){var q=window.AmazonUIPageJS||window.P,F=q._namespace||q.attributeErrors,d=F?F("MSXBooksDetailPageAsset",""):q;d.guardFatal?d.guardFatal(r)(d,window):d.execute(function(){r(d,window)})})(function(r,q,F){r.when("A","jQuery","atf").execute(function(d,a,b){if(a("#bookDescription_feature_div").length){var c=a("#outer_postBodyPS").height();a("#postBodyPS").height()>c+30?(a("#outer_postBodyPS").show(),a("#outer_postBodyPS").css("height",c),a("#psPlaceHolder").show(),a("#expandPS").show(),a("#collapsePS").hide()):
(a("#outer_postBodyPS").css("height","auto"),a("#psPlaceHolder").hide());a("#bookDescription_feature_div .a-link-expander").click(function(){a("#bdSeeAllPrompt").is(":hidden")?(a("#outer_postBodyPS").animate({height:c},500),a("#bdSeeAllPrompt").show(),a("#bdSeeLessPrompt").hide()):(a("#outer_postBodyPS").animate({height:a("#postBodyPS").height()},500),a("#bdSeeAllPrompt").hide(),a("#bdSeeLessPrompt").show());a("#bdExpanderIcon").toggleClass("rotate");return!1})}});r.when("A","jQuery","DynamicIframe",
"bookDescriptionIframe").execute(function(d,a,b,c){if(a("#bookDescription_feature_div").length){var e=function(){var b=a("#"+r).contentDocument;if(c.staticHeight&&b&&b.defaultView)var d=parseInt(c.numLines,10),e=b.find("#iframeContent"),b=b.defaultView.getComputedStyle(e,null).getPropertyValue("line-height"),b=parseFloat(b),b=Math.round(b*d);else d=document.getElementById(c.featureDiv).offsetTop,b=document.getElementById(c.imageBlockDiv).offsetTop,e=document.getElementById(c.imageBlockDiv).offsetHeight,
b=b+e-d-30,112>b&&(b=112);d=document.getElementById(c.postBodyId).offsetHeight;d>b+30?a("#"+c.seeLessPromptId).hasClass("a-hidden")?(a("#"+c.outerBodyId).height(b),a("#"+c.placeHolderId).removeClass("a-hidden"),a("#"+c.seeAllPromptId).removeClass("a-hidden")):a("#"+c.outerBodyId).height(d):(a("#"+c.outerBodyId).height(d),a("#"+c.placeHolderId).addClass("a-hidden"),a("#"+c.seeAllPromptId).removeClass("a-hidden"),a("#"+c.seeLessPromptId).addClass("a-hidden"),a("#"+c.expanderIconId).removeClass("rotate"));
b=a("#"+c.outerBodyId).height();0==f&&(f=b);b=f;d>b+30&&a("#"+c.seeLessPromptId).is(":hidden")?(a("#"+c.outerBodyId).show(),a("#"+c.outerBodyId).css("height",b),a("#"+c.placeHolderId).show(),a("#expandPS").removeClass("a-hidden"),a("#collapsePS").addClass("a-hidden")):a("#"+c.outerBodyId).css("height","auto")};"use strict";var h=null;d=c.encodedDescription;var f=0,k={},r=c.iFrameId;k.iframeId=r;k.iframeWrapperId="bookDesc_iframe_wrapper";k.overriddenCSSId="bookDesc_override_CSS";k.encodedIframeContent=
d;k.initialResizeCallback=e;h=new b(k);h.createIframe();"undefined"!==typeof h&&h instanceof b&&(a(q).resize(function(){h.resizeIframe(e)}),a(q).bind("imageResize",function(){h.resizeIframe(e)}));a("#"+c.featureDiv+" .a-link-expander").click(function(){var b="#"+c.outerBodyId,d="#"+c.seeAllPromptId,e="#"+c.seeLessPromptId,h="#"+c.expanderIconId,k="#"+c.postBodyId;a(d).hasClass("a-hidden")?(k=f,a(b).animate({height:k},500),a(d).removeClass("a-hidden"),a(e).addClass("a-hidden"),a(h).removeClass("rotate")):
(a(b).animate({height:a(k).height()},500),a(d).addClass("a-hidden"),a(e).removeClass("a-hidden"),a(h).addClass("rotate"));return!1})}});r.when("A","jQuery","ImageBlockATF","AudibleAudioPlayer","cf").execute(function(d,a,b,c){function e(a){if("undefined"!==typeof a){var b=q.ue;if(b&&b.count){var c=b.count(a)||0;b.count(a,c+1)}}}function h(){var a=q.innerWidth||document.body.offsetWidth;if(!(0>=a))if(a>b.windowWidthThreshold&&z.width()<=b.configWidths[0]){var a=b.configWidths[1],c=a/b.holderRatio,d=
b.frontImageWidth,A=b.frontImageHeight;f(a,c,d,A)}else a<b.windowWidthThreshold&&z.width()>b.configWidths[0]&&(a=b.configWidths[0],c=a/b.holderRatio,b.frontImageAspectRatio>b.holderRatio?(d=a,A=d/b.frontImageAspectRatio):(A=c,d=A*b.frontImageAspectRatio),f(a,c,d,A))}function f(c,d,A,n){if(0<c&&0<d&&0<A&&0<n){X.css("margin-left",c+b.centerColMargin).removeClass("centerColumn");Y.css("width",c);var e=d+b.containerMargin+b.flipLinkMinHeight;z.css("width",c).css("height",e);k(A,n);D.css("height",d-(d-
g.outerHeight())/2);c=(D.outerWidth()-g.outerWidth())/2;d=D.outerHeight()-g.outerHeight();t.css("top",d).css("left",c);w.css("top",d+F).css("left",c+A-w.width());a(this).trigger("imageResize");l&&l.hide()}}function k(a,b){g.css("width",a).css("height",b);var c=g.width(),n=g.height();t.css("width",c).css("height",n);"undefined"!==typeof u&&0<u.length&&(u.css("width",c).css("height",n),m.css("height",n),A&&R&&(n=m.width(),x=(c-n)/2-2,m.removeClass("ieTransition").css("left",(c-n)/2),"front"==y?m.css("transform",
"perspective(3000px) rotateY(-65deg) translateZ("+x+"px)"):m.css("transform","perspective(3000px) rotateY(90deg) translateZ("+x+"px)"),d.delay(function(){m.addClass("ieTransition")},10)))}function V(){var a=v.find(".audioSamplePopover");r.when("jQuery","a-popover","ready").execute(function(b,c){l=c.create(Z,{activate:"onclick",position:"triggerRight",inlineContent:a})});J.click(S)}function S(){l&&l.show()}function Q(a){a.bind("audioEnded",function(){K.hide();L.hide();J.show();n=0;l&&l.hide()});a.bind("audioPlaying",
function(){K.hide();J.hide();L.show();n=1;S()});a.bind("audioPaused",function(){L.hide();J.hide();K.show();n=0;l&&l.hide()})}function W(){n?H.pause():H.play()}function M(a){if("undefined"!=typeof SitbReader)if("back"==y&&SitbReader.currentBook&&SitbReader.currentBook.bookmarks){a=SitbReader.currentBook.bookmarks.getFirstAndLastPageNumberByName("Back Cover").first;var c=SitbReader.currentBook.bookmarks.getFirstAndLastPageNumberByName("Back Flap").first;a?SitbReader.LightboxActions.openReaderToPage(a):
c?SitbReader.LightboxActions.openReaderToPage(c):SitbReader.LightboxActions.openReader(b.litbData.litbReftag)}else SitbReader.LightboxActions.openReader(b.litbData.litbReftag)}function G(a){R?"click"==a.type?"front"==y?(y="back",g.removeClass("frontUnrotated frontUnrotatedHover").addClass("frontRotated"),u.removeClass("backUnrotated backUnrotatedHover").addClass("backRotated"),m.css("transform","perspective(3000px) rotateY(90deg) translateZ("+x+"px)"),p.addClass("a-hidden"),N.removeClass("a-hidden"),
O.addClass("flipToBackImgRotate"),e("booksImageFlipToBackCount")):(y="front",g.removeClass("frontRotated frontRotatedHover").addClass("frontUnrotated"),u.removeClass("backRotated backRotatedHover").addClass("backUnrotated"),m.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+x+"px)"),N.addClass("a-hidden"),p.removeClass("a-hidden"),O.removeClass("flipToBackImgRotate"),e("booksImageFlipToFrontCount")):"mouseenter"==a.type?"front"==y?(g.removeClass("frontUnrotated").addClass("frontUnrotatedHover"),
u.removeClass("backUnrotated").addClass("backUnrotatedHover"),m.css("transform","perspective(3000px) rotateY(-55deg) translateZ("+x+"px)")):(g.removeClass("frontRotated").addClass("frontRotatedHover"),u.removeClass("backRotated").addClass("backRotatedHover"),m.css("transform","perspective(3000px) rotateY(80deg) translateZ("+x+"px)")):"front"==y?(g.removeClass("frontUnrotatedHover").addClass("frontUnrotated"),u.removeClass("backUnrotatedHover").addClass("backUnrotated"),m.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+
x+"px)")):(g.removeClass("frontRotatedHover").addClass("frontRotated"),u.removeClass("backRotatedHover").addClass("backRotated"),m.css("transform","perspective(3000px) rotateY(90deg) translateZ("+x+"px)")):"click"==a.type?"front"==y?(t.removeClass("bookCanvasTransformHover").addClass("rotated"),p.addClass("a-hidden"),N.removeClass("a-hidden"),O.addClass("flipToBackImgRotate"),y="back",e("booksImageFlipToBackCount")):(t.removeClass("rotated rotatedHover"),N.addClass("a-hidden"),p.removeClass("a-hidden"),
O.removeClass("flipToBackImgRotate"),y="front",e("booksImageFlipToFrontCount")):"mouseenter"==a.type?"front"==y?t.addClass("bookCanvasTransformHover"):t.removeClass("rotated").addClass("rotatedHover"):"front"==y?t.removeClass("bookCanvasTransformHover"):t.removeClass("rotatedHover").addClass("rotated")}function I(){E.addClass("parentImage");m.addClass("bookSpine").removeClass("a-hidden");t.addClass("bookCanvasTransition");g.addClass("bookFrontTransition");d.delay(function(){t.addClass("bookCanvasTransformHover");
d.delay(function(){t.removeClass("bookCanvasTransformHover")},1500)},50)}function P(){var a=m.outerWidth(),b=g.outerWidth();x=(b-a)/2-2;m.css("left",(b-a)/2).css("transform","perspective(3000px) rotateY(-90deg) translateZ("+x+"px)");g.addClass("ieTransition ieBookShadow").css("transform-origin","50% 50% -"+a/2+"px");u.addClass("ieTransition backLanding ieBookShadow").removeClass("a-hidden").css("transform-origin","50% 50% -"+a/2+"px");m.addClass("ieTransition ieBookShadow").removeClass("a-hidden").css("transform-origin",
"50% 50% -"+a/2+"px");d.delay(function(){u.removeClass("backLanding").addClass("backUnrotated");g.addClass("frontUnrotated");m.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+x+"px)")},50);g.mouseenter(function(){m.css("transform","perspective(3000px) rotateY(-75deg) translateZ("+x+"px)")});g.mouseleave(function(){m.css("transform","perspective(3000px) rotateY(-65deg) translateZ("+x+"px)")});C.removeClass("a-hidden")}var z=a("#imageBlock"),E=z.find("#img-wrapper"),D=z.find("#imageBlockContainer"),
t=z.find("#img-canvas"),u=t.find(".backImage"),m=t.find(".sideImage"),g=t.find(".frontImage"),w=a("#imageBlockOuter").find("#sitbLogo"),C=z.find(".flipImageToBack"),v=z.find(".sampleBookAudio"),B=0,y="front",A=0,n=0,J=v.find(".audioListenText"),L=v.find(".audioPlayingText"),K=v.find(".audioPausedText"),T=v.find(".audioText"),Z=v.find(".audioPopoverTrigger"),H,p=C.find(".flipToBackText"),N=C.find(".flipToFrontText"),O=C.find(".flipToBackImg"),R=a.browser.msie||!!navigator.userAgent.match(/Trident/),
l,Y=a("#leftCol"),X=a("#centerCol"),x=0,U=a("#imageBlockOuter").find("#sitbLogoImg"),F=parseInt(z.css("margin-top"));(function(){q.ue&&q.ue.count&&ue.count("booksImageFlipToBackCount",0);q.ue&&q.ue.count&&ue.count("booksImageFlipToFrontCount",0);var n=E.offset(),e=g.offset();if(e){var l=e.top-n.top,n=e.left-n.left,e=g.outerWidth(),k=g.outerHeight(),p=E.outerHeight()-(E.outerHeight()-g.outerHeight())/2,f=m.outerWidth();E.css("position","relative");w.css("top",l+F).css("left",n+e-w.width());t.css("position",
"absolute").css("top",l).css("left",n).css("width",e).css("height",k);g.css("position","absolute").css("top","0").css("left","0");u.css("position","absolute").css("top","0").css("left","0");m.css("position","absolute").css("top","0").css("left","-"+f+"px");D.css("height",p)}b.audibleData&&b.audibleData.audioSampleSrc&&(H=new c,l={},l.audioSrc=b.audibleData.audioSampleSrc,l.audioId="img-blk-audio-sample",l.audioControllerId=v,l.flashPlayerUrl=b.audibleData.flashPlayerUrl,l.bindEventsCallback=Q,H.init(l));
e=1;l=["Perspective","TransformStyle","TransformOrigin","BackfaceVisibility","Transition"];for(n=0;n<l.length;n++)if(e){for(var e=l[n],k=["Webkit","Moz","O","ms"],p=document.createElement("div"),f=!1,r=0;r<k.length;r++)k[r]+e in p.style&&(f=f||!0);"Perspective"===e&&"WebkitPerspective"in p.style&&(f=!1,p.id="test3d",document.body.appendChild(p),3===p.offsetHeight&&(f=!0),p.parentNode.removeChild(p));e=f}B=e;l="undefined"!==typeof u&&0<u.length;(A=B&&l)?(l=g.width(),n=g.height(),0<l&&0<n&&(t.addClass("image-3d"),
u.css("width",l).css("height",n),m.css("height",n),R?P():(I(),u.addClass("bookBack").removeClass("a-hidden"),C.removeClass("a-hidden")),d.declarative("flip-action",["click","mouseenter","mouseleave"],G)),H&&H.isPlayerAvailable?C.addClass("a-span6"):C.addClass("a-span12")):t.addClass("image-2d");b&&b.litbData&&b.litbData.hasLitb&&b.litbData.litbReftag&&(U.removeClass("a-hidden"),U.click(M),t.click(M),l={hasComponents:!0,components:[{name:"mainimage"}]},"function"===typeof q.markFeatureInteractive&&
q.markFeatureInteractive("booksImageBlock",l));H&&H.isPlayerAvailable&&(A?v.addClass("a-span6"):v.addClass("a-span12"),L.hide(),K.hide(),v.removeClass("a-hidden"),T.children().click(W),l=parseInt,n=J.outerWidth(),e=L.outerWidth(),k=K.outerWidth(),p=0,0<n&&0<e&&0<k&&(p=Math.max(n,e,k)+5),(l=l(p))&&0<l&&T.css("width",l),V());b.disableResize||a(q).resize(h)})()});r.when("a-modal-handlers").execute("mark-booksimageblock-interactive-time",function(){"function"===typeof q.markFeatureInteractive&&q.markFeatureInteractive("booksImageBlock",
{hasComponents:!0,components:[{name:"thumbnail"}]})});r.when("A","jQuery","ImageBlockATF","ImageGalleryMarkup").execute(function(d,a,b){function c(){var a=b.imageGalleryData;if(a&&0<a.length){w={};C=a.length;for(var c=0;c<a.length;c++)w["ig-thumb-"+c]=a[c]}}function e(){g=I.height();0<P.length&&(g-=P.height());if(a.browser.msie&&7==a.browser.version){var b=z.outerHeight()-z.height();b&&0<b&&(g-=b)}if(g&&0<g){z.css("height",g);var b=u.height(),c=u.width();E.css("height",b).css("width",c).data("height",
b).data("width",c)}}function h(){if(0<I.length){e();k();if(0<C)for(var b=0;b<C;b++){var c="ig-thumb-"+b,c=a('\x3cdiv class\x3d"ig-thumb-image"\x3e\x3cimg class\x3d"ig-thumb-inner '+(c==B?"selected":"")+'" id\x3d"'+c+'" src\x3d"'+w[c].thumbUrl+'"\x3e\x3c/div\x3e');t.append(c)}zoomOptions=q();v.setImageData(zoomOptions);v.attachZoomEvents()}}function f(){var a=w[B].dimensions[0],b=w[B].dimensions[1];D.css("max-width",a).css("max-height",b).removeClass("image-stretch-horizontal image-stretch-vertical");
D.addClass(r(a,b))}function k(){w[B]&&(f(),D.attr("src",w[B].mainUrl))}function r(a,b){var c=E.data("width")/E.data("height"),d="image-stretch-vertical";a/b>c&&(d="image-stretch-horizontal");return d}function q(){var a={};w[B]&&(a.containerId="igInner",a.imageId="igImage",a.imageWidth=w[B].dimensions[0],a.imageHeight=w[B].dimensions[1]);return a}function Q(){w&&t.find(".ig-thumb-inner").click(function(){var b=this.id,c=a(this),d=w[b];!c.hasClass("selected")&&d&&(B=b,t.find(".selected").removeClass("selected"),
c.addClass("selected"),v.detachEvents(),D.addClass("a-hidden"),m.show(),document.getElementById("igImage").onload=y,k(),b=q(),v.setImageData(b))})}function F(){var a=d.viewport();G.closest(".a-popover-modal").css("width",.75*a.width).css("height",.75*a.height);e();v.detachEvents();f();a=q();v.setImageData(a);v.attachZoomEvents()}function M(){d.capabilities.orientation&&(d.on("orientationchange",function(){F()}),d.on("a:popover:afterHide:imageGallery",function(){d.off("a:popover:afterHide:imageGallery");
d.on("a:popover:beforeShow:imageGallery",function(){F()})}))}var G=a("#imgGalleryContent"),I=G.closest(".a-popover-wrapper"),P=I.find(".a-popover-header"),z=I.find(".a-popover-inner"),E=G.find("#igInner"),D=E.find("#igImage"),t=G.find(".ig-thumbs"),u=G.find(".ig-main-image"),m=G.find(".loading-bar"),g=0,w=null,C=0,v=new function(){function b(){p.bind("touchstart.ig touchmove.ig",function(a){c(a);p.unbind("touchstart.ig touchmove.ig");p.bind("touchmove.ig",function(a){c(a)});p.bind("touchend.ig",function(a){e.zoomOut();
p.unbind("touchstart.ig touchmove.ig touchend.ig");b()})})}function c(a){t&&a.preventDefault();var b,d={},g=f.width(),k=f.height();b=a.pageX-f.offset().left;a=a.pageY-f.offset().top;d.x=r?b*h/g-b:0;d.y=q?a*m/k-a:0;e.zoomIn(d)}var e={},g=null,k=null,h=0,m=0,f=null,p=null,r=!1,q=!1,t=d.capabilities.touch;e.setImageData=function(b){g=b.containerId;k=b.imageId;h=b.imageWidth;m=b.imageHeight;f=a("#"+g);p=a("#"+k);r=0<h&&0<f.length&&h>f.width();q=0<m&&0<f.length&&m>f.height()};e.attachZoomEvents=function(){if(r||
q)f.addClass("zoomable"),t?b():p.click(function(a){f.hasClass("zoomed-in")?(e.zoomOut(),p.unbind("mousemove")):f.hasClass("zoomed-out")&&(c(a),p.mousemove(function(a){c(a)}))})};e.zoomIn=function(a){p.css("top",-1*a.y);p.css("left",-1*a.x);f.removeClass("zoomed-out").addClass("zoomed-in")};e.zoomOut=function(){f.removeClass("zoomed-in").addClass("zoomed-out");p.css("top","auto").css("left","auto")};e.detachEvents=function(){e.zoomOut();p.unbind();f.removeClass("zoomable")};return e},B;0<G.length&&
(B="ig-thumb-0",m.hide(),c(),h(),Q(),M());var y=function(){m.hide();D.removeClass("a-hidden");v.attachZoomEvents()}});r.when("A","jQuery").execute(function(d,a){if(a("#imageBlockThumbs").length){var b=function(){var b=a("#imgThumbs"),e=b.data("a-modal"),h=d.viewport();e.width=.75*h.width;e.height=.75*h.height;b.data("a-modal",e)};"use strict";b();d.on("resize",b)}});"use strict";r.when("A","jQuery","msxUtility","ready","atf").execute(function(d,a,b){function c(c){var h=a("\x3cdiv\x3e\x3c/div\x3e").html(c);
b.digestPageStates(h);h=null;r.when("responsiveMediaTabsLoadComplete").execute(function(){k.eq(0).html(c);f.find(".olpLink").eq(0).addClass("tabHidden");f.find(".mediaMatrix").eq(0).removeClass("tabHidden");d.trigger("mediaMatrixLazyLoadComplete")});h=a(".otherSellers.mediaMatrix");0<h.length&&h.eq(0).bind("click",e)}function e(c){b.postMetric("mmt-media-matrix-glance-view");a(c.currentTarget).unbind("click",e)}var h=d.state("media-matrix-variables");if(h){var h="/gp/mediatabs/mediamatrix?"+a.param({asin:h.currentAsin,
isMediaMatrixAjaxCall:1,productGroupId:h.productGroupID}),f=a("#mediaTabsHeadings"),k=a("#mediaTab_content_all").find("#MediaMatrix"),q=a("#mediaTab_content_all").find("#MediaMatrixSlot");k&&0<k.length&&q&&0<q.length&&a.ajax({method:"GET",url:h,dataType:"text",success:function(a){a&&/\S/.test(a)?c(a):b.postMetric("mmt-media-matrix-ajax-call-fail")},error:function(a){b.postMetric("mmt-media-matrix-ajax-call-fail")}})}});"use strict";r.when("A","jQuery").register("msxUtility",function(d,a){return{digestPageStates:function(a){a.find("script[type\x3d'a-state']").each(function(a,
b){var h,f,k=b.dataset;k&&k.aState&&(h=JSON.parse(k.aState).key,f=JSON.parse(b.innerText));h&&f&&d.state(h,f)})},postMetric:function(a){if("undefined"!==typeof a){var c=q.ue;if(c){var d=c.count(a)||0;c.count(a,d+1)}}}}})});
/* ******** */
(function(d){var e=window.AmazonUIPageJS||window.P,g=e._namespace||e.attributeErrors,a=g?g("OffersBooksDetailPageAsset"):e;a.guardFatal?a.guardFatal(d)(a,window):a.execute(function(){d(a,window)})})(function(d,e,g){d.when("A","jQuery","atf").execute(function(a,b,c){var d=b("#rbbContainer");d.find(".rbbHeaderLink").attr("href","javascript:void(0);");d.find(".rbbHeader .displayNone i.prime").hide();d.find(".rbbHeader .displayNone .primeBadge").hide();d.find(".rbbHeader .ubbPrimeBadge").hide();d.find(".rbbHeader .prime-plus-price").hide();
d.find(".rbbHeader .displayNone").removeClass("displayNone");b("#rbbContainer .rbbSection.unselected .dp-accordion-inner").hide();var e=b("#buyDealSection").length;b("#rbbContainer .rbbSection .rbbHeader").click(function(a){b(a.target);a=b(this);a=a.hasClass("rbbHeader")?a:a.parents(".rbbHeader");if(a.parents(".rbbSection").hasClass("selected"))return!1;d.find(".selected .a-icon-radio-active").removeClass("a-icon-radio-active").addClass("a-icon-radio-inactive");d.find(".selected .offer-price").removeClass("a-color-price a-size-medium").addClass("a-color-base a-size-base");
d.find("i.a-icon.prime").hide();d.find(".primeBadge").hide();d.find(".ubbPrimeBadge").hide();var c=d.find(".prime-plus-price-grid");c.hasClass("hidden")?c.removeClass("hidden").show():c.addClass("hidden").hide();d.find(".prime-plus-price").show();a.parents(".rbbSection").removeClass("unselected").addClass("selected");a.parents(".rbbSection").toggleClass("dp-accordion-active",500);a.find(".a-icon-radio-inactive").removeClass("a-icon-radio-inactive").addClass("a-icon-radio-active");a.find(".offer-price").removeClass("a-color-base a-size-base").addClass("a-color-price a-size-medium");
a.find("#priceBadgeValue").removeClass("a-size-medium").addClass("a-size-base");a.find("i.a-icon.prime").show();a.find(".primeBadge").show();a.find(".prime-plus-price").hide();b("#rbbContainer .rbbSection .rbbContent").find(".offer-price").removeClass("a-color-base").addClass("a-color-price");a.find(".ubbPrimeBadge").show();var g=b(this).attr("id"),m,p;d.find(".rbbSection").each(function(a,c){b(c).find(".rbbHeader")[0].id==g?m=b(c):b(c).hasClass("selected")&&(p=b(c))});p.find(".rbbContent").slideUp(500,
function(){p.removeClass("selected").addClass("unselected");p.toggleClass("dp-accordion-active",500)});m.find(".rbbContent").slideDown(500);b.browser.msie&&7==parseInt(b.browser.version,10)&&(m.find(".rbbContent").css("display","inline"),setTimeout(function(){m.find(".rbbContent").css("display","block")},505));if(e&&"undefined"!=typeof UDPDealView)if(b("#gbld_header_message").show(),"buyDealSection"==g)UDPDealView.prototype.onSelectLDBuybox();else UDPDealView.prototype.onSelectRegularBuybox();return!0})});
d.when("A","jQuery").execute(function(a,b){b("#one-click-button-ubb, #usedbuyBox #add-to-cart-button-ubb").click(function(){var a=b("#addToCart"),d=a.attr("action").replace("ref=dp_start-bbf_1_glance","ref=dp_start-ubbf_1_glance");a.attr("action",d);return!0});d.when("a-popover").execute(function(c){var d=b("#usedItemConditionInfoLink"),e=c.create(d,{width:250,position:"triggerBottom",activate:a.capabilities.touch?"onmousemove":"onclick",closeButton:!1,popoverLabel:"Used condition details",name:"usedItemConditionDetailsPopover",
dataStrategy:"preload"});d.mouseleave(function(){e.hide()})})})});
/* ******** */
(function(k){var l=window.AmazonUIPageJS||window.P,m=l._namespace||l.attributeErrors,e=m?m("PInfoBooksDetailPageAsset",""):l;e.guardFatal?e.guardFatal(k)(e,window):e.execute(function(){k(e,window)})})(function(k,l,m){k.when("A","jQuery","atf").execute(function(e,a,w){var h,d=0;k.when("DPClientLogger").execute(function(){"undefined"!=typeof l.DPClientLogger&&(h=new l.DPClientLogger.ImpressionLogger("dpbxapps","bxapps-atfMarker",!0,!0))});a("#bookDetails_feature_div .hero-more").click(function(b){b.preventDefault();
b=a(this).attr("data-popupID");var g=a("#"+b),f=a(this).offset().left+a(this).width()/2,c=a("#popupContent").offset().left,f=(f-c)/a("#popupContent").width()*100;a("#"+b+" .pointer").css({left:f+"%"});a("#popupContent .details-popup").filter(":visible").length?a("#popupContent .details-popup").filter(":visible").attr("id")!==b?(a("#popupContent .details-popup").filter(":visible").slideToggle(300),g.slideToggle(300)):g.slideUp(300):(g.slideDown(300),a(this).hasClass("hero-more")&&a("html,body").animate({scrollTop:a("#bookDetails_feature_div").offset().top-
50},600));h&&!d&&(h.logImpression("ma-books-br-details"),d=1)});a("#bookDetails_feature_div .moreNarratorLink").click(function(){if(location.pathname.replace(/^\//,"")==this.pathname.replace(/^\//,"")||location.hostname==this.hostname){var b=a(this.hash),b=b.length?b:a("[name\x3d"+this.hash.slice(1)+"]");b.length&&a("html,body").animate({scrollTop:b.offset().top},1E3);return!1}});a("#bookDetails_feature_div .details-popup button").click(function(b){a(this).parent().slideUp(300)})});k.when("A","jQuery",
"atf").execute(function(e,a,k){function h(){var d=parseInt(a("#byline").width()),b=0;a("#byline .author").each(function(){a(this).is(".notFaded")&&(b+=a(this).outerWidth())});b+=a("#byline .more").outerWidth();if(b>d){var g=a("#byline .author.notFaded").length;a(a("#byline .author.notFaded").get().reverse()).each(function(c){b>d&&c<g-1&&(c=a(this).width(),a(this).removeClass("notFaded"),a(this).fadeOut(10,function(){a(this).hide()}),b-=c,a("#byline .moreCount").html(a("#byline .author").length-a("#byline .author.notFaded").length),
a("#byline .more").addClass("notFaded").fadeIn(10))})}else if(b<d&&a("#byline .author.notFaded").length<a("#byline .author").length){var f=d-b;a("#byline .author").each(function(){if(!a(this).hasClass("notFaded")){var c=a(this).outerWidth();c<=f?(f-=c,a(this).addClass("notFaded").fadeIn(10),c=a("#byline .author").length-a("#byline .author.notFaded").length,0===c?a("#byline .more").removeClass("notFaded").fadeOut(10):(a("#byline .moreCount").html(c),a("#byline .more").addClass("notFaded").fadeIn(10))):
f=0}})}}a("#byline .showMoreLink").click(function(){a("#byline .author").each(function(){a(this).hasClass("notFaded")||a(this).addClass("notFaded").fadeIn(0);a("#byline .more").removeClass("notFaded").fadeOut(0)});return!1});a("#byline .contributorNameID").mouseenter(function(){var d=a(this).attr("data-asin"),b={},g="isAjaxComplete_"+d,f="isAjaxInProgress_"+d,c=e.state("popoverImage-state");b.entityID=d;"1"!==c[g]&&"1"!==c[f]&&(a.ajax({url:"/gp/product/utility/by-line/book-contributor-details/ajax/author-image.html",
data:b,dataType:"html",timeout:1E3,success:function(b){a("#contributorImageContainer"+d).get(0).innerHTML=b;c[g]="1";e.state("popoverImage-state",c)},error:function(){c[f]="0";e.state("popoverImage-state",c)}}),c[f]="1",e.state("popoverImage-state",c))});(function(d){var b=parseInt(d.width()),g=parseInt(d.find(".more").outerWidth()),f=0;a("#byline .author").each(function(){a(this).is(".notFaded")&&(f+=a(this).outerWidth())});a("#byline .more").attr("data-width",g);var c=b-g;if(c>f)d.find(".author").each(function(){var b=
a(this).index();3<=parseInt(b)?(b=a(this).outerWidth(),a(this).attr("data-width",b),b<c?(c-=b,a(this).addClass("notFaded"),a(this).fadeIn("slow")):(c=0,a(this).fadeOut("slow"))):(b=a(this).outerWidth(),a(this).attr("data-width",b),c-=b)});else{var e=a("#byline .author.notFaded").length;a(a("#byline .author.notFaded").get().reverse()).each(function(b){c<f&&b<e-1&&(b=a(this).outerWidth(),f-=b,a(this).fadeOut("slow").removeClass("notFaded"))})}b=d.find(".author").length-d.find(".author.notFaded").length;
0<b&&(d.find(".moreCount").html(b),d.find(".more").fadeIn("slow"),d.find(".more").addClass("notFaded"))})(e.$("#byline"));a(l).resize(function(){h()})});k.when("A","jQuery","atf").execute(function(e,a,k){function h(){var d=parseInt(a("#bylineInfo").width()),b=0;a("#bylineInfo .author").each(function(){a(this).is(".notFaded")&&(b+=a(this).outerWidth())});b+=a("#bylineInfo .more").outerWidth();if(b>d){var e=a("#bylineInfo .author.notFaded").length;a(a("#bylineInfo .author.notFaded").get().reverse()).each(function(c){b>
d&&c<e-1&&(c=a(this).width(),a(this).removeClass("notFaded"),a(this).fadeOut(10,function(){a(this).hide()}),b-=c,a("#bylineInfo .moreCount").html(a("#bylineInfo .author").length-a("#bylineInfo .author.notFaded").length),a("#bylineInfo .more").addClass("notFaded").fadeIn(10))})}else if(b<d&&a("#bylineInfo .author.notFaded").length<a("#bylineInfo .author").length){var f=d-b;a("#bylineInfo .author").each(function(){if(!a(this).hasClass("notFaded")){var b=a(this).outerWidth();b<=f?(f-=b,a(this).addClass("notFaded").fadeIn(10),
b=a("#bylineInfo .author").length-a("#bylineInfo .author.notFaded").length,0===b?a("#bylineInfo .more").removeClass("notFaded").fadeOut(10):(a("#bylineInfo .moreCount").html(b),a("#bylineInfo .more").addClass("notFaded").fadeIn(10))):f=0}})}}a("#bylineInfo .showMoreLink").click(function(){a("#bylineInfo .author").each(function(){a(this).hasClass("notFaded")||a(this).addClass("notFaded").fadeIn(0);a("#bylineInfo .more").removeClass("notFaded").fadeOut(0)});return!1});a("#bylineInfo .contributorNameID").mouseenter(function(){var d=
a(this).attr("data-asin"),b={},g="isAjaxComplete_"+d,f="isAjaxInProgress_"+d,c=e.state("popoverImage-state");b.entityID=d;"1"!==c[g]&&"1"!==c[f]&&(a.ajax({url:"/gp/product/utility/by-line/book-contributor-details/ajax/author-image.html",data:b,dataType:"html",timeout:1E3,success:function(b){a("#contributorImageContainer"+d).get(0).innerHTML=b;c[g]="1";e.state("popoverImage-state",c)},error:function(){c[f]="0";e.state("popoverImage-state",c)}}),c[f]="1",e.state("popoverImage-state",c))});(function(d){var b=
parseInt(d.width()),e=parseInt(d.find(".more").outerWidth()),f=0;a("#bylineInfo .author").each(function(){a(this).is(".notFaded")&&(f+=a(this).outerWidth())});a("#bylineInfo .more").attr("data-width",e);var c=b-e;if(c>f)d.find(".author").each(function(){var b=a(this).index();3<=parseInt(b)?(b=a(this).outerWidth(),a(this).attr("data-width",b),b<c?(c-=b,a(this).addClass("notFaded"),a(this).fadeIn("slow")):(c=0,a(this).fadeOut("slow"))):(b=a(this).outerWidth(),a(this).attr("data-width",b),c-=b)});else{var h=
a("#bylineInfo .author.notFaded").length;a(a("#bylineInfo .author.notFaded").get().reverse()).each(function(b){c<f&&b<h-1&&(b=a(this).outerWidth(),f-=b,a(this).fadeOut("slow").removeClass("notFaded"))})}b=d.find(".author").length-d.find(".author.notFaded").length;0<b&&(d.find(".moreCount").html(b),d.find(".more").fadeIn("slow"),d.find(".more").addClass("notFaded"))})(e.$("#bylineInfo"));a(l).resize(function(){h()})});k.when("A","jQuery","DynamicIframe","ProductDescriptionData","cf").execute(function(e,
a,k,h){function d(){t=0;var a=Math.min(m,p.length);g(0,a)}function b(){0<n.length&&0<q.length&&(r="collapsed",n.removeClass("a-hidden"),n.click(function(){"collapsed"===r?(v?q.animate({height:"show"}):(q.removeClass("extraReviews"),g(t,p.length),v=1),n.removeClass("collapsed").addClass("expanded"),r="expanded"):(q.animate({height:"hide"}),n.removeClass("expanded").addClass("collapsed"),r="collapsed")}))}function g(b,c){var d;for(d=b;d<c;d++){var e={};e.iframeId="er_iframe_"+d;e.iframeWrapperId="er_iframe_wrapper_"+
d;e.iframeContainerId="er_container_"+d;e.iframeExpanderId="er_expander_"+d;e.iframeColumnId="er_column_"+d;var g=e,h=p[d],m="\x3ch3 class\x3d'erSource'\x3e"+h.source+"\x3c/h3\x3e\x3cdiv class\x3d'erContent'\x3e"+h.content+"\x3c/div\x3e";h.footnote&&(m=m+"\x3cem class\x3d'erFootnote'\x3e"+h.footnote+"\x3c/em\x3e");g.encodedIframeContent=m;e.initialResizeCallback=f;g=e;h={};h.id=a("#"+g.iframeId);h.column=a("#"+g.iframeColumnId);h.wrapper=a("#"+g.iframeWrapperId);h.container=a("#"+g.iframeContainerId);
h.expander=a("#"+g.iframeExpanderId);h.iframeObj=new k(g);h.state="full";g=h;u[e.iframeId]=g;g.column.removeClass("extraReviews");g&&"undefined"!=typeof g.iframeObj&&"function"==typeof g.iframeObj.createIframe&&g.iframeObj.createIframe();l(g);t++}}function f(a){(a=u[a])&&170<a.wrapper.outerHeight()&&(a.container.css("height",140),a.expander.removeClass("a-hidden expanded").addClass("collapsed"),a.state="partial")}function c(a){(a=u[a])&&"full"===a.state&&a.container.css("height",a.wrapper.outerHeight())}
function l(b){if(b&&"undefined"!=typeof b.iframeObj&&"function"==typeof b.iframeObj.resizeIframe)e.on("resize",function(){b.iframeObj.resizeIframe(c)});b&&b.expander&&b.expander.click(function(){"partial"===b.state?(b.container.animate({height:b.wrapper.outerHeight()}),b.expander.removeClass("collapsed").addClass("expanded"),b.state="full"):(b.container.animate({height:140}),b.expander.removeClass("expanded").addClass("collapsed"),a("html, body").animate({scrollTop:b.container.offset().top-20}),b.state=
"partial")})}var p=h.encodedReviews,m=parseInt(h.reviewsPerRow),t=0,v=0;h=a("#productDescription-multiColumn");var u={},n,q,r;0<h.length&&p&&0<p.length&&m&&(n=h.find(".reviewsExpander"),q=h.find(".seeMoreProductReviews"),d(),b())})});
/* ******** */
(function(d){var e=window.AmazonUIPageJS||window.P,g=e._namespace||e.attributeErrors,a=g?g("TwisterBooksDetailPageAsset"):e;a.guardFatal?a.guardFatal(d)(a,window):a.execute(function(){d(a,window)})})(function(d,e,g){d.when("A","jQuery","atf").execute(function(a,b){a.on.ready(function(){function c(a,c,d,e,f){b(a).slideToggle(300);b(c).slideToggle(300);b(d).toggleClass("tmmShowPrompt tmmHidePrompt");b(e).toggleClass("tmmShowPrompt tmmHidePrompt");b(f).toggleClass("rotate")}function f(a){a.position();
a.width();b(".swatchElement");a.find(".swatchElement").each(function(){b(this).attr("data-width",b(this).width());x+=b(this).width()});b("#formats").find(".a-row").removeClass("nonJSFormats")}function g(){var a=b("#formats"),c=a.width()-40,d=0,e=0;a.find(".swatchElement").each(function(){b(this).is(":visible")?d+=b(this).width():e++});var f=b(a.find(".swatchElement").get().length),k=a.find(".swatchElement .audibleTitle").length,l=0<f.length&&4<=f[0];(B||z)&&l&&k&&(l=n(d,c),d-=l,B?u.count("mediaMatrixUIOptimization",
1):u.count("mediaMatrixUIOptimizationResizeAndSpillOver",1));d>c?b(a.find(".swatchElement:visible").get().reverse()).each(function(){var a=0,f=!1;b(this).find(".format").hasClass("a-button-selected")?(a=b(this).prev(".swatchElement").width(),f=b(this).prev(".swatchElement").is(":hidden"),b(this).prev(".swatchElement").hide()):(a=b(this).width(),f=b(this).is(":hidden"),b(this).hide());e++;f||(d-=a);return d>c}):d<c&&a.find(".swatchElement").each(function(){if(b(this).is(":hidden")){var a=b(this).width();
a<=c-d&&(b(this).show(),d+=a,e--)}});0==e&&h(d,c,f,x);(z||C)&&k&&(b("#tmmSwatches").css({display:"inline-block","white-space":"normal"}),C&&u.count("mediaMatrixtwisterSpillOver",1),b(a.find(".swatchElement").get().reverse()).each(function(){b(this).is(":hidden")&&b(this).show();b(this).addClass("marginTop")}));!A&&k&&(b.post("/hz/audible/wl",{audible_weblabs:"ADBL_TWISTER_RESIZE_116490"}),A=1);w||(f=b("#audibleTwisterWeblabs"),null!=f&&f.length&&null!=f.data("weblabs")&&(f=f.data("weblabs"),a=a.find(".swatchElement:visible .audibleTitle").length,
f.length&&a&&b.post("/hz/audible/wl",{audible_weblabs:f},function(a){w=!0})))}function n(a,c){var d=b("#formats"),e=0;b(d.find(".swatchElement").get().reverse()).each(function(){var d=k(b(this)),f=b(this).width(),f=f>d?f-d:0;if(a>c&&0<f||b(this).is(":hidden"))m(b(this),d),e+=f,a-=f});return e}function h(a,c,d,e){var f=Math.round(0<d.length?(c-a)/d[0]:0)-10,f=0<f?f:0;0<f&&b("#formats").find(".swatchElement").each(function(){var a=parseInt(b(this).attr("data-width")),d=k(b(this))+(0<f?f:0),a=e<c?a+
1:Math.min(d,a);m(b(this),a)});return f}function k(a){var b=a.find("#kuBadge").length;a=a.find(".a-icon-kindle-unlimited").length;return 0<b||0<a?150:117}function m(a,b){a.addClass("resizedSwatchElement");a.css({width:b+"px"})}var p=0,t=0,w=!1,v,u=e.ue,x=0,A=0,B=b("#twisterResizeWeblab")?b("#twisterResizeWeblab").data("weblabs"):null,z=b("#twisterResizeAndSpillOver")?b("#twisterResizeAndSpillOver").data("weblabs"):null,C=b("#twisterSpillOver")?b("#twisterSpillOver").data("weblabs"):null,y=function(a){"undefined"!=
typeof a&&(v=new a.ImpressionLogger("dpbxapps","bxapps-atfMarker",!0,!0))};"undefined"!=typeof amznJQ?amznJQ.available("DPClientLogger",function(){y(e.DPClientLogger)}):d.when("DPClientLogger").execute(y);a.declarative("tmm-see-more-editions-click",["click"],function(d){var f=d.data,g=f.metabindingUrl;if(d.$target.hasClass("a-link-expander")||d.$target.parent().hasClass("a-link-expander")){var f=f.metabindingPlaceHolder,h="#metabinding_row_top_"+f,k="#metabinding_row_bottom_"+f,l="#editionsSeePrompt_"+
f,m="#editionsHidePrompt_"+f,n="#editionsIcon_"+f,p="isAjaxComplete_"+f,q="isAjaxInProgress_"+f;d="#tmmSpinnerDiv_"+f;var v=a.state("mediamatrix-state"),f=v["url_"+f].replace(/&amp;/g,"&");b("#formats .tmmErrorClass").hide();"1"===v[p]||"1"===v[q]?c(h,k,l,m,n):(a.ajax(f,{method:"get",success:function(){v[p]="1";a.state("mediamatrix-state",v);c(h,k,l,m,n)},indicator:b(d),error:function(){b($tmmErrorDiv).show();v[q]="0";a.state("mediamatrix-state",v)}}),v[q]="1",a.state("mediamatrix-state",v))}else"#"!==
g&&(e.location=g)});0<b("#formats > .a-link-expander").length&&u&&u.count&&u.count("mediaMatrixExpanderPresent",1);b("#formats > .a-link-expander").click(function(){c("#tmmSwatches","#twister","#showMoreFormatsPrompt","#hideMoreFormatsPrompt","#formatsIcon");t||(u&&u.count&&u.count("mediaMatrixExpanderClicked",1),t=1);v&&b("#twister").is(":visible")&&!p&&(v.logImpression("tmm-show-more-formats-viewed"),p=1)});b("#formats.responsive").each(function(){f(b(this))});var q=a.state("mediamatrixState"),
D="false";"undefined"!==typeof q&&"undefined"!==typeof q.swatchWrap&&(D=q.swatchWrap);"true"!=D&&(g(),a.on("resize",g));b("#formats .unselected .format").mouseenter(function(){b(this).find(".a-color-secondary").addClass("a-color-price").removeClass("a-color-secondary")}).mouseleave(function(){b(this).find(".a-color-price").addClass("a-color-secondary").removeClass("a-color-price")});b("#landingItemRentalLink").attr("href","javascript:document.getElementById('rentBuySection').click();")})})});
/* ******** */
(function(c){var b=window.AmazonUIPageJS||window.P,d=b._namespace||b.attributeErrors,a=d?d("DetailPageBookProductDescriptionAssets",""):b;a.guardFatal?a.guardFatal(c)(a,window):a.execute(function(){c(a,window)})})(function(c,b,d){});
/* ******** */
